//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowTEXMonitor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Textos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Textos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlowTEXMonitor.Textos", typeof(Textos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Abrir {
            get {
                return ResourceManager.GetString("Abrir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value! Allowed values: 0x01 to 0x7F.
        /// </summary>
        internal static string AlertaI2CAddrInvalido {
            get {
                return ResourceManager.GetString("AlertaI2CAddrInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the I2C address?.
        /// </summary>
        internal static string AlertaTrocaI2C {
            get {
                return ResourceManager.GetString("AlertaTrocaI2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to change the address.
        /// </summary>
        internal static string FalhaTrocaI2C {
            get {
                return ResourceManager.GetString("FalhaTrocaI2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Fechar {
            get {
                return ResourceManager.GetString("Fechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address successfully changed!.
        /// </summary>
        internal static string SucessoTrocaI2C {
            get {
                return ResourceManager.GetString("SucessoTrocaI2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value.
        /// </summary>
        internal static string TituloAlertaI2CAddrInvalido {
            get {
                return ResourceManager.GetString("TituloAlertaI2CAddrInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I2C address change.
        /// </summary>
        internal static string TituloAlterarI2C {
            get {
                return ResourceManager.GetString("TituloAlterarI2C", resourceCulture);
            }
        }
    }
}
